---
name: Bug report
about: Create a report to help us improve
title: ''
labels: bug
assignees: ''

---

**OutsetaPy version**
Please state the version of OutsetaPy you're using.

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. outseta = OutsetaApiClient(subdomain='xxx',apiKey='xxx', secretKey='xxx')
2. async def main():
    accounts = await outseta.crm.accounts.get_all()
3. You now get the error: "....."

**Expected behavior**
A clear and concise description of what you expected to happen.

**System Information**
 - OS/IAAS: [e.g. Windows 10 x64, Linux Ubuntu, macOS 12, Azure App Services, AWS]
 - Python Distribution: [e.g. Python.org 3.9, Anaconda3 2021.11 3.9, ActivePython 3.9]

**Additional context**
Add any other context about the problem here.
